#pragma once
#define WAIT_THREAD_TERMINATING_ON

#define CAMERA_WITH_BAD_PIXELS_SN "1209017"
#define CAMERA_WITH_BAD_PIXELS_BAD_PIXEL_1 { 223, 25 } 
#define CAMERA_WITH_BAD_PIXELS_FIRST_GOOD_PIXEL_OFF_FOR_BAD_PIXEL_1 1

